name = "ttrade-worker"
main = "worker/src/worker.ts"
compatibility_date = "2026-04-03"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "ttrade-db"
database_id = "34853f80-bf36-4156-b15d-b32a0e58b60d"
migrations_dir = "worker/migrations"
